# Generated by Django 5.2.8 on 2025-11-28 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профиля')),
                ('profile_id', models.CharField(max_length=50, unique=True, verbose_name='ABCP profileId')),
            ],
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.FileField(upload_to='tender/input/', verbose_name='Входной файл (brand/sku/qty)')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='tender/output/', verbose_name='Результат проценки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('done', 'Готово'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tender.clientprofile', verbose_name='Профиль клиента')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
