# Generated by Django 5.2.8 on 2025-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderjob',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
