# Generated by Django 5.2.8 on 2025-11-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_tenderjob_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача тендерной проценки', 'verbose_name_plural': 'Задачи тендерной проценки'},
        ),
        migrations.RemoveField(
            model_name='tenderjob',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='tenderjob',
            name='output_file',
        ),
        migrations.AddField(
            model_name='tenderjob',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='tenders/output/', verbose_name='Результирующий XLSX-файл'),
        ),
        migrations.AlterField(
            model_name='tenderjob',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_jobs', to='tender.clientprofile', verbose_name='Профиль клиента'),
        ),
        migrations.AlterField(
            model_name='tenderjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tenderjob',
            name='input_file',
            field=models.FileField(upload_to='tenders/input/', verbose_name='Входной XLSX-файл'),
        ),
        migrations.AlterField(
            model_name='tenderjob',
            name='log',
            field=models.TextField(blank=True, default='', verbose_name='Лог выполнения'),
        ),
        migrations.AlterField(
            model_name='tenderjob',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('done', 'Готово'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
