# Generated by Django 5.2.8 on 2025-11-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_alter_tenderjob_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача проценки', 'verbose_name_plural': 'Задачи проценки'},
        ),
    ]
